# Copyright (c) 2026 NFUPT4. All rights reserved.
# This source code is licensed under the CC BY-NC-SA
# (Creative Commons Attribution-NonCommercial-NoDerivatives) License.
# This software is protected by copyright law. Reproduction, distribution, or use for commercial
# purposes is prohibited without the organization's permission. If you have any questions or require
# permission, please contact NFUPT4 https://gitee.com/nfupt4.

wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
